### ISSUE TITLE
Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push.

### ISSUE THREAD

**Issue by NagarajuKamatham** [twilio/twilio-voice-ios#112]
### Description

Hello Twilio team,

We developed an app(make/receive voip calls between users) using TwilioVoice, and it's working fine. Recently we're getting an error **NSInternalInconsistencyException in PKPushRegistry** in latest iOS 16.3.1, even thorough we're reporting call to CallKit.

can you help me out on this issue, why we get this only in latest versions of iOS.

#### Xcode

Xcode - 14.3

#### iOS Version

iOS - 16.3.1

#### iOS Device

iPhone 11

**Comment by janakirampalepu** [comment]
@bobiechen-twilio  Can you quickly check and let us know the root cause for the app crash.

Our app crashes rarely once in 3-4 weeks and we get this exception. But for others it's working.

**NSInternalInconsistencyException PKPushRegistry
Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.**

**Comment by bobiechen-twilio** [comment]
Hi

Please refer to this [migration guide](https://github.com/twilio/twilio-voice-ios/blob/Releases/iOS-13-Migration-Guide.md) or follow the example code from the [Voice iOS SDK quickstart](https://github.com/twilio/voice-quickstart-ios) - make sure the application is reporting PushKit VoIP push notifications to CallKit as incoming call as soon as the incoming push is received by the app, otherwise resulting in policy violation termination.
