### ISSUE TITLE
Push notification from twilio

### ISSUE THREAD

**Issue by nikhiltekwani09** [twilio/twilio-voice-ios#117]
[What you expect to happen]

Every new call invitation from Twilio is received as a VoIP notification in the iOS application, prompting the application to display the Call Kit interface with accept and reject buttons. The connection for the invitation is established only after the accept button on the Call Kit interface is pressed. However, it is expected to receive the invitation as a regular push notification instead of a VoIP notification. In my case, the server sends the VoIP notification whenever a new call is initiated, and the Twilio invitation is anticipated after accepting the offer received from my server.
 

[What actually happens]

As both my application server and Twilio are sending VoIP notifications, it leads to a poor user experience and makes it challenging to handle Twilio VoIP notifications when a call is already ongoing on the Call Kit interface.

[What percentage of the time does it reproduce?]

In Every Call

 
 

### Versions

 

All relevant version information for the issue.

 

#### Voice iOS SDK

 

6.8.1

 

#### Xcode

 

14.2

 

#### iOS Version

 

16.1.1 IOS Version

 

#### iOS Device

 

iPhone 12 Pro

**Comment by bobiechen-twilio** [comment]
Hi @nikhiltekwani09 

Thanks for reaching out. If I am understanding this correctly, you want to control what information is sent inside the VoIP push notifications to your mobile client when your application makes Programmable Voice call to the mobile client.

In this case, I would suggest not calling the `TwilioVoice.register()` method from the iOS client. By doing this, there will only be one VoIP push notification to the client and no more CallKit UX glitch. You will also need to include the information telling your mobile client how to connect the call, for example using the [Twilio queue calls](https://www.twilio.com/docs/voice/queue-calls) so the mobile client knows how/where to dial back and connect the incoming call.

However, your application is now responsible of handling call state updates, especially the cancelation that was handled by the Voice iOS SDK. This was done by an internal connection established by the SDK when the `TwilioVoice.handleNotification()` method is called. Keep in mind this will require some sort of connection between the mobile client and your backend service since sending another VoIP push notification will require another CallKit report, which is not the ideal UX (well I guess you can send a regular APN push but I am not sure if it works when the app is in the active state).

Let me know if the above makes sense and we are more than happy to hear feedback and suggestion so we can improve the SDK integration experience.

-bobie

**Comment by nikhiltekwani09** [comment]
Hello @bobiechen-twilio , I apologize for any misunderstanding. To clarify, I'm not interested in customizing the message within the VoIP notification, but rather I want to explore alternative methods of detecting if an invite has been generated,  without relying on a VoIP notification.

Can the invite be sent in a form of apns notification and not VoIP notification.

**Comment by bobiechen-twilio** [comment]
@nikhiltekwani09 

According to Apple's VoIP best practice, using the VoIP (PushKit) push notification would guarantee the most reliable notification delivery experience which is crucial to VoIP applications and for now Twilio will continue on this route as the means of incoming call experience. That being said, we do acknowledge that PushKit/CallKit integration can sometimes be cumbersome plus the lack of flexibility of the current Programmable Voice push notification integration, we are entertaining ideas of how to provide events to application developers along the path of incoming call delivery. We appreciate your suggestion and definitely look forward to more in the future.

-bobie

**Comment by nikhiltekwani09** [comment]
@bobiechen-twilio I hope you're doing well. 

I m looking for an update on the invitation event.

In our current setup, an offer is initiated using a VoIP push notification. However, upon acceptance of the offer, I anticipate receiving a Twilio invite. My preference is for this invite to be managed separately from VoIP notifications. The objective is to process it silently without displaying a VoIP notification, particularly when another VoIP call is already in progress, having been received as an offer from our backend.
