### ISSUE TITLE
Preserve call session when user taps on notification

### ISSUE THREAD

**Issue by aksthelion** [twilio/twilio-voice-ios#47]
I've an app in which I've voice call feature. During a call, call disconnects when user taps on a new push notification which is linked to a view in this app. Is it possible to keep call connected when user taps on this notification and is redirected to another view?

I know this question may not be related to this SDK as such but in a real life situation it's a normal scenario.

**Comment by bobiechen-twilio** [comment]
Hi @aksthelion 

If my assumption is correct, a view-controller or UI component own the `TVOCall` object and when another view-controller is presented, the call object along with first view-controller is not retained and destroyed, therefore the call got disconnected. Does this describe your situation?

In the debugging console do you see any SDK error message indicating that the call is disconnected due to some error?

Thanks,
bobie

**Comment by aksthelion** [comment]
Thanks for reply. Your assumption is correct. I didn't check for error, I don't think there will be any error as you have already explained why it gets disconnected. Do you have any suggestions/hints on how to fix this issue so that calls don't disconnect when another view is presented?

**Comment by bobiechen-twilio** [comment]
Hi @aksthelion 

Since the Voice SDK is replying on the application to retain the `TVOCall` object throughout the lifecycle of the call, the application needs to implement some sort of "store" to keep the ownership of the call objects (actually the `TVOCallInvite` objects as well). Ideally this "store" component should be sharable between UI or other logical components.

**Comment by aksthelion** [comment]
Thanks will look into it.

**Comment by BhavikWings** [comment]
Is it possible to integrate voice calls using FCM in iOS? I have two applications one is customer app and the other is the driver app. And also both app in android as well as how we can handle this situation.
I want to call between the customer to the driver.

We need to create 4 SID or what and how it will works? Can you please guide me

Thank you

**Comment by bobiechen-twilio** [comment]
Hi @BhavikWings 

Currently the Voice iOS SDK requires Apple's VoIP Service for delivering incoming call notifications. You can follow [the steps](https://github.com/twilio/voice-quickstart-ios#bullet7) in the iOS quickstart to set up the VoIP certificate and enable your Voice iOS app to receive push notifications, that way your iOS application can also receive incoming calls or connect calls with your Android app as long as they are using the same Twilio account SID.

Since this question is not related to the original issue here, can you please open a new issue for the discussion? Thanks.
