### ISSUE TITLE
How to show top bar status bar for a call in foreground state

### ISSUE THREAD

**Issue by aksthelion** [twilio/twilio-voice-ios#50]
During a call, when app enters background state we show call progress bar (green) in status bar. Is it possible to show this same green status bar when app is in foreground when we navigate away from the call view? Something similar to what WhatsApp does?

Please refer to this discussion 
https://stackoverflow.com/questions/39853195/like-skype-application-how-to-show-top-bar-status-bar-at-ongoing-call-in-foregr

![CallProgressStatusBar](https://user-images.githubusercontent.com/45408351/81430253-0a58de80-9157-11ea-984c-f2f78bf25497.jpg)

**Comment by bobiechen-twilio** [comment]
Hi @aksthelion 

The UI presentation is up to the application so the SDK doesn't have control over it. I found a similar thread where people are discussing implementing the same component: https://stackoverflow.com/questions/38738195/how-to-show-double-height-green-statusbar-in-call-in-foreground-app-on-device

I am going to close the issue since it's not an SDK issue.
