### ISSUE TITLE
Feature Request: Lite Bundle for App Clips

### ISSUE THREAD

**Issue by marcato15** [twilio/twilio-voice-ios#65]
With the release of App Clips in iOS 14 it’d be nice to offer a basic Video call feature in an App Clip. The uncompressed bundle size is required to be below 10 mb which means including just the current Twilio Video SDK is too big for an app clip. Is there a subset of functionality that could be provided in a lite version of the library to make a basic video call functionality available in an App Clip?

**Comment by bobiechen-twilio** [comment]
Hi @marcato15

Thanks for reaching out. It seems that you might be using the Video iOS SDK, but I think the same applies to both the Programmable Video and Voice SDKs - since socket connection is not supported in App Clips bundle, unfortunately the app cannot connect to rooms or calls using the SDK. For more information you can check out the **App Clips** section here: https://github.com/twilio/twilio-voice-ios/issues/56
