### ISSUE TITLE
Call an invalid phone number, call ends without any prompt feedback 

### ISSUE THREAD

**Issue by jocelynlih** [twilio/twilio-voice-ios#8]
### Description

Call an invalid phone number, call ends without any prompt feedback.

### Steps to Reproduce

1. Call an invalid phone number: the phone number is formatted correctly, but the phone number is invalid or not existed. An example number is 888 555 5512
2. Call ended without any notice

#### Code

Sample code 

#### Expected Behavior

1. It will be great to hear a audio message to remind you the phone number is invalid. 

2. Or if option 1 is not possible, it’s nice to have a callback so we can show a proper alert in the app. 

#### Actual Behavior

Call ends without any feedback

#### Reproduces How Often

100%

#### Logs

```
// Log output when the issue occurs
```

### Versions

2.0.*

#### Voice iOS SDK

2.0 from cocoapods 

#### Xcode

Xcode 10

#### iOS Version

iOS 11, 12

#### iOS Device

iPhone

**Comment by bchen-twilio** [comment]
Hi @jocelynlih 

Thanks for reporting the issue. I've tried the example number you provided and from what I can see the mobile client only got a normal `no-answer` result and the call ended without any error since the parent call leg (mobile client <--> Twilio service) was connected successfully based on the actions specified in the TwiML response.
The error callback will only be raised when the SDK failed to establish the connection between the mobile client and the Twilio Voice service, for example signaling connection failed due to poor network or developer's TwiML app server returned some malformed TwiML response, or TwiML server endpoint not even reachable, or invalid TwiML application SID, etc.

Hope this answers your question.

Cheers,
Bobie

**Comment by jocelynlih** [comment]
Thx @bchen-twilio, so the problem is the current user experience seems not clear (If the typo occurs when entering a phone number, it’s not clear that the phone number is invalid. It’s connected and then ended. ) It will be great to have some error code from the SDK side so we can use that to inform user inside our app.
