### ISSUE TITLE
unregister notification for read_timeout / write_timeout failed

### ISSUE THREAD

**Issue by abhinavsingh** [twilio/twilio-voice-ios#84]
### Description

App constantly keeps logging following warnings:

<img width="818" alt="Screen Shot 2021-10-19 at 3 25 17 PM" src="https://user-images.githubusercontent.com/126065/137887516-604b14b8-2bc9-4e1f-9019-88e12f689114.png">

### Steps to Reproduce

These logs can be seen periodically when Twilio SDK is enabled.  If we disable Twilio SDK, these log lines disappear.  We have read Apple forum which seem to hint they are harmless "most" of the times.  

#### Expected Behavior

No log noise.

#### Actual Behavior

Lots of log noise

#### Reproduces How Often

Always

#### Voice iOS SDK

`'TwilioVoice', '~> 6.3.0'`

#### iOS Version

14.8

#### iOS Device

iPhone 12 Pro

**Comment by bobiechen-twilio** [comment]
Hi @abhinavsingh 

Thanks for reaching out. As you have figured out, the messages seem to be generated by Apple and don't seem to affect the SDK functionality.

Closing issue since this appears to be an OS issue but please feel free to reach out if you run into trouble integrating the Voice SDK.

Cheers,
-bobie
